name: 1-Checkout-Build-Artifact

on:
  workflow_dispatch:
  schedule:
    # Runs "Every Sunday" (see https://crontab.guru)
    - cron: '15 8 * * Sun'
jobs:
  Checkout-Build-Artifact-Dockerize:

    runs-on: windows-2022

# Checkout-Build-Artifact

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    
    - name: Build App
      run: dotnet build app
    
    - name: Zip Application Files 
      uses: vimtor/action-zip@v1
      with:
        files: app/bin/Debug/netcoreapp3.1/
        dest: verademodotnetcore.zip
    
    - name: Upload Application Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: VeraDemoDotNetCoreAppArtifact
        path: app/bin/Debug/netcoreapp3.1/
        
  Dockerize-Publish:

    runs-on: ubuntu-latest

    steps:
    # Dockerize-Publish
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Pull Ubuntu MSSQL Docker Image Dependency
      run: docker pull mcr.microsoft.com/mssql/server:2017-CU24-ubuntu-16.04      

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v3.2.0
      with:
        context: .
        push: true
        tags: veracodedemolabs/vd-dotnetcore-gh:latest

